# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       java: corretto11
#   pre_build:
#     commands:
#       - echo Esta es la etapa pre_build...
#   build:
#     commands:
#       - echo Comienza el Build, started on `date`
#       - mvn install
#   post_build:
#     commands:
#       - echo Post_build finalizado!
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar

version: 0.2

phases:
  pre_build:
    commands:
      - echo Conectandose a Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Generando la imagen Docker...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Finalizado el Build
      - echo Publicando la imagen Docker en ECR...
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push 011067815571.dkr.ecr.us-east-1.amazonaws.com/m3m0x-dockerhub:latest

#Funciona! Para publicar imagen en DockerHub con secrets

# version: 0.2
# env:
#   secrets-manager:
#     DOCKERHUB_PASS: "DOCKERHUB_KEYS:DOCKER_PASS"
#     DOCKERHUB_USERNAME: "DOCKERHUB_KEYS:DOCKER_USERNAME"
# phases:
#   pre_build:
#     commands:
#       - echo Logging in to Docker Hub...
#       - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS    
#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Building the Docker image...
#       - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
#       - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker image...
#       - docker push $IMAGE_REPO_NAME:$IMAGE_TAG