version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Esta es la etapa pre_build...
  build:
    commands:
      - echo Comienza el Build, started on `date`
      - mvn install
  post_build:
    commands:
      - echo Post_build finalizado!
artifacts:
  files:
    - target/messageUtil-1.0.jar